version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myflaskapp
      POSTGRES_USER: myflaskuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@example.com  # Change this
      PGADMIN_DEFAULT_PASSWORD: mypassword          # Change this
    ports:
      - "5050:80"  # Expose pgAdmin port

volumes:
  pgdata:
